# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-30 18:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180627_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uploaded_by',
            field=models.CharField(default=datetime.datetime(2018, 6, 30, 18, 2, 10, 370072, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(max_length=255, null=True, upload_to='images/'),
        ),
    ]
